In [1]:
from keras.datasets import mnist
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
# %matlplotlib inline
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

Using TensorFlow backend.
c:\users\thinkpad\anaconda3\envs\cnn\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\thinkpad\anaconda3\envs\cnn\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\thinkpad\anaconda3\envs\cnn\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\thinkpad\anaco

In [2]:
(x_train, y_train),(x_test,y_test) = mnist.load_data()

# save input image dimensions
#image dimensions are 28 x 28

x

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


In [5]:
num_classes = 10 #there are 10 class lables
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [6]:
model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
     activation='relu',
     input_shape=(img_rows, img_cols, 1)))

In [7]:
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

In [8]:
model.compile(loss='categorical_crossentropy',
      optimizer='adam',
      metrics=['accuracy'])
batch_size = 128
epochs = 10


In [9]:
print(y_test.shape)
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
# model.save("test_model.h5")

(10000, 10)
Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 113s 2ms/step - loss: 0.2394 - accuracy: 0.9266 - val_loss: 0.0525 - val_accuracy: 0.9822
Epoch 2/10
60000/60000 [==============================] - 113s 2ms/step - loss: 0.0858 - accuracy: 0.9742 - val_loss: 0.0383 - val_accuracy: 0.9869
Epoch 3/10
60000/60000 [==============================] - 115s 2ms/step - loss: 0.0640 - accuracy: 0.9806 - val_loss: 0.0300 - val_accuracy: 0.9900
Epoch 4/10
60000/60000 [==============================] - 116s 2ms/step - loss: 0.0498 - accuracy: 0.9851 - val_loss: 0.0291 - val_accuracy: 0.9906
Epoch 5/10
60000/60000 [==============================] - 115s 2ms/step - loss: 0.0422 - accuracy: 0.9869 - val_loss: 0.0294 - val_accuracy: 0.9904
Epoch 6/10
60000/60000 [==============================] - 113s 2ms/step - loss: 0.0359 - accuracy: 0.9887 - val_loss: 0.0268 - val_accuracy: 0.9916
Epoch 7/10
60000/60000 [==========================

In [ ]:
image_index = 35
image = x_train[image_index]
image = image.reshape(1, img_rows, img_cols, 1)
from keras.models import load_model
model = load_model("test_model.h5")
-+
# predict digit
prediction = model.predict(image)
print(prediction.argmax())




In [1]:
model.summary()

NameError: name 'model' is not defined

In [1]:
import imageio
import numpy as np
from PIL import image
# import matplotlib.pyplot as plt

im = plt.imread("crop.jpg")
image = im.thumbnail(28,28)
image = image.reshape(1, img_rows, img_cols, 1)
from keras.models import load_model
model = load_model("test_model.h5")

# predict digit
prediction = model.predict(image)
print(prediction.argmax())

ImportError: cannot import name 'image' from 'PIL' (c:\users\thinkpad\anaconda3\envs\cnn\lib\site-packages\PIL\__init__.py)

In [0]:
from keras.datasets import mnist
from keras.utils import to_categorical
import numpy as np
import matplotlib.pyplot as plt
# %matlplotlib inline
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten, Conv2D, MaxPooling2D

(x_train, y_train),(x_test,y_test) = mnist.load_data()

# save input image dimensions
#image dimensions are 28 x 28

img_rows, img_cols = 28, 28
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

#division by 255 because each pixel may range from 0 to 255
x_train = x_train / 255
x_test = x_test / 255

num_classes = 10 #there are 10 class lables
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
     activation='relu',
     input_shape=(img_rows, img_cols, 1)))

model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss='categorical_crossentropy',
      optimizer='adam',
      metrics=['accuracy'])
batch_size = 128
epochs = 10

print(y_test.shape)
model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs,
          verbose=1,
          validation_data=(x_test, y_test))
score = model.evaluate(x_test, y_test, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])
# model.save("test_model.h5")